# docker-compose.yml
version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - SPRING_DATASOURCE_USERNAME=RM557167
      - SPRING_DATASOURCE_PASSWORD=120799
      - JWT_SECRET=meusegredoultrasecretoparajwt123456789
    restart: always